TRUNCATE TABLE cfg_categories;

INSERT INTO cfg_categories (module_key, image_url, description, create_datetime, update_datetime)
VALUES ('AUTOMOBILE_CATEGORY_KEY', 'https://voursa.s3.amazonaws.com/images/1739293692670_automobiles-icon.svg',
        'Automobile category',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('ELECTRONICS_CATEGORY_KEY', 'https://voursa.s3.amazonaws.com/images/1739293857281_electronics-icon.svg',
        'Electronics category',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('REAL_ESTATE_CATEGORY_KEY', 'https://voursa.s3.amazonaws.com/images/1739294042074_real-estate-icon.svg',
        'Real Estate category',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('FASHION_AND_BEAUTY_CATEGORY_KEY', 'https://voursa.s3.amazonaws.com/images/1739294259764_clothings-icon.svg',
        'Fashion and Beauty category', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('FURNITURE_CATEGORY_KEY', 'https://voursa.s3.amazonaws.com/images/1739293910176_furnitures-iconsvg.svg',
        'Furniture category',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('OTHER_CATEGORY_KEY', 'https://voursa.s3.amazonaws.com/images/1739294517152_others.svg', 'Other category',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO cfg_states (name_key) VALUES
    ('STATE_HODH_CHARGUI'),
    ('STATE_HODH_EL_GHARBI'),
    ('STATE_ASSABA'),
    ('STATE_GORGOL'),
    ('STATE_BRAKNA'),
    ('STATE_TRARZA'),
    ('STATE_ADRAR'),
    ('STATE_DAKHLET_NOUADHIBOU'),
    ('STATE_TAGANT'),
    ('STATE_GUIDIMAGHA'),
    ('STATE_TIRIS_ZEMMOUR'),
    ('STATE_INCHIRI'),
    ('STATE_NOUAKCHOTT_OUEST'),
    ('STATE_NOUAKCHOTT_NORD'),
    ('STATE_NOUAKCHOTT_SUD');
INSERT INTO cfg_cities (city_key, state_id) VALUES
    ('CITY_ADELBAGROU', 1),
    ('CITY_NBEIKET_L', 1),
    ('CITY_OUALATA', 1),
    ('CITY_NEMA', 1),
    ('CITY_DJIGUENNI', 1),
    ('CITY_BASSIKNOU', 1),
    ('CITY_TIMBEDRA', 1),
    ('CITY_AMOURJ', 1),
    ('CITY_AIOUN', 2),
    ('CITY_TAMCHEKET', 2),
    ('CITY_KOUBENNI', 2),
    ('CITY_TINTANE', 2),
    ('CITY_TOUIL', 2),
    ('CITY_BARKEOL', 3),
    ('CITY_BOUMDEID', 3),
    ('CITY_KANKOUSSA', 3),
    ('CITY_KIFFA', 3),
    ('CITY_GUEROU', 3),
    ('CITY_KAEDI', 4),
    ('CITY_MAGHAMA', 4),
    ('CITY_MBOUT', 4),
    ('CITY_LEXEIBA', 4),
    ('CITY_MONGUEL', 4),
    ('CITY_ALEG', 5),
    ('CITY_BABABE', 5),
    ('CITY_MBAGNE', 5),
    ('CITY_MAGTALAHJAR', 5),
    ('CITY_BOGHE', 5),
    ('CITY_MALE', 5),
    ('CITY_TEKANE', 6),
    ('CITY_MEDERDRA', 6),
    ('CITY_ROSSO', 6),
    ('CITY_OUAD_NAGA', 6),
    ('CITY_KEUR_MACEN', 6),
    ('CITY_RKIZ', 6),
    ('CITY_BOUTILIMIT', 6),
    ('CITY_AOUJEFT', 7),
    ('CITY_ATAR', 7),
    ('CITY_OUADANE', 7),
    ('CITY_CHINGUITTI', 7),
    ('CITY_NOUADHIBOU', 8),
    ('CITY_CHAMI', 8),
    ('CITY_TICHIT', 9),
    ('CITY_MOUDJERIA', 9),
    ('CITY_TIDJIKJA', 9),
    ('CITY_GHABOU', 10),
    ('CITY_SELIBABY', 10),
    ('CITY_OULD_YENGE', 10),
    ('CITY_WOMPOU', 10),
    ('CITY_ZOUERAT', 11),
    ('CITY_FDERICK', 11),
    ('CITY_BIR_MOGHREIN', 11), 
    ('CITY_BENNECHAB', 12),
    ('CITY_AKJOUJT', 12),
    ('CITY_KSAR', 13),
    ('CITY_SEBKHA', 13),
    ('CITY_TEVRAGH_ZEINA', 13),
    ('CITY_TOUJOUNINE', 14),
    ('CITY_TEYARET', 14),
    ('CITY_DAR_NAIM', 14),
    ('CITY_ARAFAT', 15),
    ('CITY_EL_MINA', 15),
    ('CITY_RIYADH', 15);